### ISSUE TITLE
Payu Dev environment numpy import error

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/payu-condaenv#28]
The  `payu/dev` environment at `/g/data/vk83/prerelease`, runs into cftime import errors at the `payu run` pbs job submission.

From local testing using micromamba environments on gadi, installing `cftime` using conda, before the pip install of payu seems to avoid the errors.  

Full error log:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/g/data/vk83/prerelease/apps/payu/dev/bin/payu-run", line 5, in <module>
    from payu.subcommands.run_cmd import runscript
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/subcommands/run_cmd.py", line 4, in <module>
    from payu import cli
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/cli.py", line 22, in <module>
    from payu.models import index as supported_models
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/models/__init__.py", line 1, in <module>
    from payu.models.access import Access
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/models/access.py", line 26, in <module>
    import payu.calendar as cal
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/calendar.py", line 5, in <module>
    import cftime
  File "/home/189/jb4202/.local/lib/python3.9/site-packages/cftime/__init__.py", line 1, in <module>
    from ._cftime import (datetime, real_datetime,
Traceback (most recent call last):
  File "/g/data/vk83/prerelease/apps/payu/dev/bin/payu-run", line 5, in <module>
    from payu.subcommands.run_cmd import runscript
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/subcommands/run_cmd.py", line 4, in <module>
    from payu import cli
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/cli.py", line 22, in <module>
    from payu.models import index as supported_models
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/models/__init__.py", line 1, in <module>
    from payu.models.access import Access
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/models/access.py", line 26, in <module>
    import payu.calendar as cal
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.9/site-packages/payu/calendar.py", line 5, in <module>
    import cftime
  File "/home/189/jb4202/.local/lib/python3.9/site-packages/cftime/__init__.py", line 1, in <module>
    from ._cftime import (datetime, real_datetime,
  File "src/cftime/_cftime.pyx", line 1, in init cftime._cftime
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

**Comment by jo-basevi** [comment]
It was an error with my setup. It was using libraries in `/.local` in the submission job. After running pip uninstall to clean up locally installed packages then loading the prerelease environment, and the run submission job worked fine.

This error wasn't caught before the run submission, as `PYTHONUSERSITE` was set in  the module file to disable including libraries from `~/.local`. This setting doesn't carry over to the `payu run` submission.

**Comment by jo-basevi** [comment]
Closing this as it wasn't an error with the prerelease dev environment

**Comment by jo-basevi** [comment]
Closing this as it wasn't an error with the payu/dev environment
